"""Add new models

Revision ID: 2a4fece191b8
Revises: 79db9313338f
Create Date: 2024-12-23 23:48:06.950240

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = "2a4fece191b8"
down_revision: Union[str, None] = "79db9313338f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "employees",
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column(
            "access_level",
            sa.Enum("ADMIN", "DEFAULT", name="employeeaccesslevel"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_employees_id"), "employees", ["id"], unique=False)
    op.create_table(
        "employee_images",
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("file_id", sa.String(), nullable=False),
        sa.Column(
            "image_vector", pgvector.sqlalchemy.vector.VECTOR(dim=3), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_employee_images_id"), "employee_images", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_employee_images_id"), table_name="employee_images")
    op.drop_table("employee_images")
    op.drop_index(op.f("ix_employees_id"), table_name="employees")
    op.drop_table("employees")
    # ### end Alembic commands ###
