"""Update Vector

Revision ID: 7b14485800a7
Revises: cef650b484e0
Create Date: 2025-01-08 17:59:51.121011

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = "7b14485800a7"
down_revision: Union[str, None] = "cef650b484e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employee_images",
        "image_vector",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=128),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employee_images",
        "image_vector",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=128),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=3),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
